version: 2

project_name: diffr

builds:
  - env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - formats: [tar.gz]
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^Merge"

homebrew_casks:
  - name: diffr
    homepage: "https://github.com/imrajdas/diffr"
    description: "Compare two directories or files in the browser or on the CLI"
    skip_upload: auto
    binaries:
      - diffr
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/diffr"]
          end
    repository:
      owner: imrajdas
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
